Repository arnav0309/Personal-Website, pull requests merged in 2021-10, with the labels that each got.

#6 hello anand
  index.html
Labels: hactoberfest-accepted

#7 Add files via upload
  bordersort.cpp
Labels: hactoberfest-accepted

#8 hactober tag
  cityTravel.java
  nongreatEquations.java
Labels: hactoberfest-accepted

#9 Strings
  large strings.c
Labels: hacktoberfest-accepted

#2 updated css
  CSS/styles.css
Labels: hactoberfest-accepted, hacktoberfest-accepted

#10 Add files via upload
  diameter.cpp
Labels: hacktoberfest-accepted

#11 Add files via upload
  HackWifi.java
Labels: hacktoberfest-accepted
